use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Sync backend selection and options (`[sync]` section).
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SyncConfig {
    /// Which sync backend to use (default: `auto`).
    #[serde(default)]
    pub backend: SyncBackendKind,
    /// Remote name used by the git backend (default: `"origin"`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub remote: Option<String>,
    /// Branch name (default: current HEAD branch).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub branch: Option<String>,
    /// Stable per-device identifier embedded in git commit messages.
    ///
    /// Should be set only in the user-level config (not the shared workspace
    /// config) so each device retains its own identity even after syncing.
    /// Auto-generated by the host application on first use via
    /// [`SyncConfig::ensure_device_id`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_id: Option<Uuid>,
}

impl SyncConfig {
    /// Effective remote name (falls back to `"origin"`).
    pub fn remote(&self) -> &str {
        self.remote.as_deref().unwrap_or("origin")
    }

    /// Ensure `device_id` is set.  If absent, a random UUID v4 is generated
    /// and stored in `self`.  Returns `true` when a new ID was generated.
    ///
    /// The caller is responsible for persisting the config after this call.
    pub fn ensure_device_id(&mut self) -> bool {
        if self.device_id.is_none() {
            self.device_id = Some(Uuid::new_v4());
            true
        } else {
            false
        }
    }
}

/// Supported sync backend variants.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum SyncBackendKind {
    /// Auto-detect: use git if the workspace is inside a git repository,
    /// otherwise no sync (local-only).  This is the default.
    #[default]
    Auto,
    /// Explicitly disable sync — local-only even inside a git repository.
    None,
    /// Git-based sync (commit → pull → push).
    Git,
}
