use serde::{Deserialize, Serialize};
use uuid::Uuid;

// ── WorkspaceSyncConfig ──────────────────────────────────────────────────────

/// Per-workspace sync settings.
///
/// These settings may vary between workspaces (e.g. different remotes for
/// different projects) and are stored in the user config under `[sync]`.
/// In the future they may also be read from a workspace-level file.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct WorkspaceSyncConfig {
    /// Which sync backend to use (default: `auto`).
    #[serde(default)]
    pub backend: SyncBackendKind,
    /// Remote name used by the git backend (default: `"origin"`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub remote: Option<String>,
    /// Branch name (default: current HEAD branch).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub branch: Option<String>,
    /// How often to automatically run git sync, in minutes.
    ///
    /// When set, the `watch` command triggers a git sync cycle
    /// (commit → pull → push) at this interval.
    /// When unset or `0`, automatic periodic git sync is disabled.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sync_interval_minutes: Option<u32>,
}

impl WorkspaceSyncConfig {
    /// Effective remote name (falls back to `"origin"`).
    pub fn remote(&self) -> &str {
        self.remote.as_deref().unwrap_or("origin")
    }

    /// Returns the git sync interval as a [`std::time::Duration`], or `None`
    /// if periodic sync is disabled (`sync_interval_minutes` is unset or `0`).
    pub fn sync_interval(&self) -> Option<std::time::Duration> {
        self.sync_interval_minutes
            .filter(|&m| m > 0)
            .map(|m| std::time::Duration::from_secs(m as u64 * 60))
    }
}

// ── UserSyncConfig ───────────────────────────────────────────────────────────

/// Per-device (user-level) sync settings.
///
/// These settings are device-specific and are shared across all workspaces
/// opened on the same device.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct UserSyncConfig {
    /// Stable per-device identifier embedded in git commit messages.
    ///
    /// Should be set only in the user-level config (not a shared workspace
    /// config) so each device retains its own identity even after syncing.
    /// Auto-generated by the host application on first use via
    /// [`UserSyncConfig::ensure_device_id`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_id: Option<Uuid>,
}

impl UserSyncConfig {
    /// Ensure `device_id` is set. If absent, a random UUID v4 is generated
    /// and stored in `self`. Returns `true` when a new ID was generated.
    ///
    /// The caller is responsible for persisting the config after this call.
    pub fn ensure_device_id(&mut self) -> bool {
        if self.device_id.is_none() {
            self.device_id = Some(Uuid::new_v4());
            true
        } else {
            false
        }
    }
}

// ── SyncConfig ───────────────────────────────────────────────────────────────

/// Combined sync configuration — workspace + user settings flattened into the
/// `[sync]` TOML section.
///
/// The TOML representation is flat (no sub-tables):
///
/// ```toml
/// [sync]
/// backend = "git"
/// remote = "origin"
/// sync_interval_minutes = 15
/// device_id = "..."
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SyncConfig {
    #[serde(default, flatten)]
    pub workspace: WorkspaceSyncConfig,
    #[serde(default, flatten)]
    pub user: UserSyncConfig,
}

impl SyncConfig {
    /// Effective remote name (falls back to `"origin"`).
    pub fn remote(&self) -> &str {
        self.workspace.remote()
    }

    /// Returns the git sync interval as a [`std::time::Duration`], or `None`
    /// if periodic sync is disabled.
    pub fn sync_interval(&self) -> Option<std::time::Duration> {
        self.workspace.sync_interval()
    }

    /// Ensure `device_id` is set. Returns `true` when a new ID was generated.
    ///
    /// The caller is responsible for persisting the config after this call.
    pub fn ensure_device_id(&mut self) -> bool {
        self.user.ensure_device_id()
    }
}

// ── SyncBackendKind ──────────────────────────────────────────────────────────

/// Supported sync backend variants.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum SyncBackendKind {
    /// Auto-detect: use git if the workspace is inside a git repository,
    /// otherwise no sync (local-only).  This is the default.
    #[default]
    Auto,
    /// Explicitly disable sync — local-only even inside a git repository.
    None,
    /// Git-based sync (commit → pull → push).
    Git,
}
